export interface Level {
  id: number
  title: string
  desc: string       // 任务描述
  text: string       // 待匹配的文本
  targets: string[]  // 必须匹配到的字符串（全部匹配才过关）
  forbid?: string[]  // 不能匹配到的字符串
  hint: string
  tip?: string       // 过关后显示的知识点
}

export const LEVELS: Level[] = [
  {
    id: 1,
    title: '第一关：找到 hello',
    desc: '匹配文本中所有的 "hello"',
    text: 'hello world\nhello regex\ngoodbye world',
    targets: ['hello', 'hello'],
    hint: '直接输入要匹配的文字',
    tip: '正则最基本的用法：字面量匹配，直接写字符串就能匹配对应文字。',
  },
  {
    id: 2,
    title: '第二关：找数字',
    desc: '匹配文本中所有的数字（0-9）',
    text: 'abc 123 def 456 ghi 7',
    targets: ['1', '2', '3', '4', '5', '6', '7'],
    hint: '\\d 匹配单个数字',
    tip: '\\d 是数字字符类的简写，等价于 [0-9]。',
  },
  {
    id: 3,
    title: '第三关：完整数字串',
    desc: '匹配所有连续的数字串（不是单个数字）',
    text: 'price: 100, count: 42, id: 9999',
    targets: ['100', '42', '9999'],
    hint: '\\d+ 匹配一个或多个数字',
    tip: '+ 是量词，表示"一个或多个"。\\d+ 就是匹配连续的数字。',
  },
  {
    id: 4,
    title: '第四关：找单词',
    desc: '匹配所有英文单词',
    text: 'foo bar123 baz hello-world test',
    targets: ['foo', 'bar', 'baz', 'hello', 'world', 'test'],
    hint: '[a-z]+ 匹配小写字母序列',
    tip: '[a-z] 是字符范围，匹配 a 到 z 的任意一个字母。',
  },
  {
    id: 5,
    title: '第五关：找空行',
    desc: '匹配文本中的空行（只有换行，没有内容）',
    text: 'line one\n\nline three\n\nline five',
    targets: ['\n', '\n'],
    hint: '^$ 匹配空行，需要开启多行模式 m',
    tip: '^ 匹配行首，$ 匹配行尾。^$ 在多行模式下匹配空行。',
  },
  {
    id: 6,
    title: '第六关：匹配邮箱',
    desc: '从文本中提取所有邮箱地址',
    text: '联系我们：admin@heycron.com 或 support@example.org，禁止发送垃圾邮件。',
    targets: ['admin@heycron.com', 'support@example.org'],
    hint: '[\\w.]+@[\\w.]+',
    tip: '\\w 匹配字母、数字和下划线，等价于 [a-zA-Z0-9_]。',
  },
  {
    id: 7,
    title: '第七关：手机号码',
    desc: '匹配所有中国大陆手机号（11位，1开头）',
    text: '张三：13812345678，李四：19987654321，座机：010-12345678',
    targets: ['13812345678', '19987654321'],
    hint: '1[3-9]\\d{9}',
    tip: '{n} 是精确数量限定符，\\d{9} 表示恰好 9 个数字。',
  },
  {
    id: 8,
    title: '第八关：IP 地址',
    desc: '匹配文本中的 IPv4 地址',
    text: '服务器 IP：192.168.1.1，备用：10.0.0.255，无效：999.999.999.999',
    targets: ['192.168.1.1', '10.0.0.255', '999.999.999.999'],
    hint: '\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}',
    tip: '{1,3} 表示 1 到 3 个，\\.  用反斜杠转义点号（.号在正则中是通配符）。',
  },
  {
    id: 9,
    title: '第九关：提取域名',
    desc: '从 URL 中提取域名部分（如 example.com）',
    text: 'https://heycron.com/regex\nhttp://www.example.org/path\nhttps://api.github.com/users',
    targets: ['heycron.com', 'www.example.org', 'api.github.com'],
    hint: '(?<=https?://)([\\w.]+)',
    tip: '(?<=...) 是正向后行断言（lookbehind），匹配前面有指定内容但不把它包含在结果里。',
  },
  {
    id: 10,
    title: '第十关：HTML 标签',
    desc: '匹配所有 HTML 标签（包括开闭标签）',
    text: '<div class="box"><p>Hello</p><img src="a.png"/></div>',
    targets: ['<div class="box">', '<p>', '</p>', '<img src="a.png"/>', '</div>'],
    hint: '<[^>]+>',
    tip: '[^>] 是否定字符类，匹配除 > 以外的任意字符。',
  },
  {
    id: 11,
    title: '第十一关：捕获组',
    desc: '匹配日期格式 YYYY-MM-DD，并捕获年月日',
    text: '生日：1990-05-20，入职：2023-01-15，今天：2024-12-31',
    targets: ['1990-05-20', '2023-01-15', '2024-12-31'],
    hint: '(\\d{4})-(\\d{2})-(\\d{2})',
    tip: '() 创建捕获组，可以单独提取括号内匹配的内容，在替换时用 $1 $2 引用。',
  },
  {
    id: 12,
    title: '第十二关：非贪婪',
    desc: '匹配 <b> 标签内的内容（不能跨标签）',
    text: '<b>粗体文字</b>普通文字<b>另一段</b>',
    targets: ['<b>粗体文字</b>', '<b>另一段</b>'],
    hint: '<b>.*?</b>',
    tip: '? 放在量词后面变为非贪婪模式，尽可能少地匹配字符。.*? 比 .* 更"克制"。',
  },
  {
    id: 13,
    title: '第十三关：单词边界',
    desc: '只匹配单独的单词 "cat"，不匹配 "catch" 或 "tomcat"',
    text: 'I have a cat. My cat is cute. I catch a catfish. tomcat is software.',
    targets: ['cat', 'cat'],
    forbid: ['catch', 'catfish', 'tomcat'],
    hint: '\\bcat\\b',
    tip: '\\b 是单词边界，确保匹配的是完整单词而不是某个单词的一部分。',
  },
  {
    id: 14,
    title: '第十四关：或运算',
    desc: '匹配所有颜色词：red、green 或 blue',
    text: 'The red fox jumps over the green hill into the blue sky. Redwood is not matched.',
    targets: ['red', 'green', 'blue'],
    hint: '\\b(red|green|blue)\\b',
    tip: '| 是"或"运算符，(red|green|blue) 匹配三者之一。',
  },
  {
    id: 15,
    title: '第十五关：密码校验',
    desc: '匹配强密码：至少8位，包含大小写字母和数字',
    text: 'weak\nPassword1\nAbc12345\ntooshort1A\n123456789\nGoodPass99',
    targets: ['Password1', 'Abc12345', 'GoodPass99'],
    hint: '^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d).{8,}$',
    tip: '(?=...) 是正向前行断言（lookahead），不消耗字符，只检查后面是否满足条件。多个 (?=...) 可以同时生效。',
  },
  {
    id: 16,
    title: '第十六关：重复捕获',
    desc: '匹配连续重复的单词（如 "the the"）',
    text: 'this is is a test. the the problem. no repeat here.',
    targets: ['is is', 'the the'],
    hint: '\\b(\\w+) \\1\\b',
    tip: '\\1 是反向引用，引用第一个捕获组匹配到的内容。\\b(\\w+) \\1\\b 匹配重复的单词。',
  },
  {
    id: 17,
    title: '第十七关：提取 JSON 值',
    desc: '提取 JSON 中所有字符串值（引号内的内容）',
    text: '{"name":"Alice","city":"Beijing","role":"admin"}',
    targets: ['Alice', 'Beijing', 'admin'],
    hint: '(?<="\\w+":")[^"]+',
    tip: '结合后行断言和否定字符类，可以精准提取特定位置的内容。',
  },
  {
    id: 18,
    title: '第十八关：Cron 表达式',
    desc: '匹配合法的 cron 表达式（5段，空格分隔）',
    text: '0 9 * * 1\n*/5 * * * *\n0 0 1 1 *\nnot a cron\n1 2 3',
    targets: ['0 9 * * 1', '*/5 * * * *', '0 0 1 1 *'],
    hint: '^([\\d*/,-]+\\s){4}[\\d*/,-]+$',
    tip: '用 ^ 和 $ 锚定整行，确保整个字符串符合格式而不只是其中一部分。',
  },
  {
    id: 19,
    title: '第十九关：SQL 注入检测',
    desc: '检测常见 SQL 注入关键字（不区分大小写）',
    text: "SELECT * FROM users\nDROP TABLE orders\nnormal input\nUNION SELECT 1,2,3\ndelete from logs",
    targets: ['SELECT * FROM users', 'DROP TABLE orders', 'UNION SELECT 1,2,3', 'delete from logs'],
    hint: '/(?i)(select|insert|update|delete|drop|union).*/gm 或用 flag: gi',
    tip: '正则 flag i 表示不区分大小写。在 JavaScript 中写作 /pattern/gi。',
  },
  {
    id: 20,
    title: '第二十关：终极挑战',
    desc: '提取 Markdown 链接的文字和 URL（格式：[文字](url)）',
    text: '访问 [Hey Cron](https://heycron.com) 和 [GitHub](https://github.com) 了解更多。',
    targets: ['[Hey Cron](https://heycron.com)', '[GitHub](https://github.com)'],
    hint: '\\[[^\\]]+\\]\\([^)]+\\)',
    tip: '恭喜通关！你已掌握正则表达式的核心用法。去 heycron.com/regex 用可视化工具练习更多吧！',
  },
]
